panda:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint1

  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint2
    
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint3
    
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint4
    
  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint5
    
  joint6_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint6
    
  joint7_position_controller:
    type: position_controllers/JointPositionController
    joint: panda_joint7
    
  joint_leftfinger_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_finger_joint1
    pid: {p: 5, i: 0, d: 3, i_clamp: 1}
  joint_rightfinger_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_finger_joint2
    pid: {p: 5, i: 0, d: 3, i_clamp: 1}
  
  # panda_hand_controller:
  #   type: effort_controllers/JointTrajectoryController
  #   joints:
  #     - panda_finger_joint1
  #   gains:
  #     panda_finger_joint1 : {p: 10000, i: 0, d: 3, i_clamp: 1}

  #   constraints:
  #     goal_time: 2.0
  #     stopped_position_tolerance: 0
  #     stopped_velocity_tolerance: 0
    
  #   state_publish_rate: 100
  
  # joint_rightfinger_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: panda_finger_joint2
  #   pid: {p: 5, i: 0, d: 3, i_clamp: 1}
